_wandb:
    value:
        cli_version: 0.24.2
        e:
            3ndcrzpq5e7b6e6w2rbg7g12ffj2mwj3:
                codePath: assignment1-basics/Train/train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1081101176832"
                        used: "17194672128"
                email: acd66@foxmail.com
                executable: /home/acd66/project/CS336/assignment1-basics/.venv/bin/python3
                git:
                    commit: e72ad8220c959fedb7739281e760a75780229c93
                    remote: https://github.com/July-h5kf3/CS336.git
                host: mkdir
                memory:
                    total: "16439799808"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/acd66/project/CS336/assignment1-basics/Train/train.py
                python: CPython 3.12.3
                root: /home/acd66/project/CS336/assignment1-basics/Train
                startedAt: "2026-02-09T13:11:49.727877Z"
                writerId: 3ndcrzpq5e7b6e6w2rbg7g12ffj2mwj3
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
model:
    value:
        RoPE_theta: 10000
        context_length: 256
        d_ff: 1344
        d_model: 512
        num_heads: 16
        num_layers: 4
        vocab_size: 10000
training:
    value:
        batch_size: 32
        checkpoint_dir: /home/acd66/project/CS336/assignment1-basics/tests/outputs/checkpoints
        device: cpu
        log_interval: 100
        max_grad_norm: 1
        max_lr: "1e-3"
        min_lr: "1e-5"
        save_interval: 1000
        total_steps: 40000
        warmup_steps: 500
        weight_decay: "1e-2"
